server:
  port: 8080
  servlet:
    context-path: /api

group:
  name: group-name

spring:
  profiles:
    include:
      - secret

  datasource:
    url: jdbc:mysql://ecomate.crgoui2zsut0.ap-northeast-2.rds.amazonaws.com:3306/ecomate
    driver-class-name: com.mysql.cj.jdbc.Driver

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  security:
    filter:
      order: 2

  redis:
    port: 6379

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        #show_sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug

springdoc:
  api-docs:
    groups:
      enabled: true
  swagger-ui:
    operations-sorter: method
  paths-to-match: /**
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

cloud:
  aws:
    region:
      static: ap-northeast-2
    stack:
      auto: false

s3-directory:
  board: board
  challenge: challenge
  profile: profile

logging.level.com.amazonaws.util.EC2MetadataUtils: error