server:
  port: 8080
  servlet:
    context-path: /api
spring:
  profiles:
    include:
      - secret
  datasource:
    url: jdbc:mysql://ecomate.crgoui2zsut0.ap-northeast-2.rds.amazonaws.com:3306/ecomate
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
